version: "3.8"
services:
 reverse-proxy:
    container_name: WitPaKul_Proxy
    image: nginx 
    ports:
    - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
   default:
    external:
        name: witpakul_network
